name: my first workflow file creation
on:
   push:
      branches:
          -main
jobs:
   run-json-load:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name : set up python version
          uses : actions/setup-python@v4
          with:
              python-version : '3.14'
        - name: set up dependencies
          run : |
                python -m pip install --upgrade pip
                pip install requests beautifulsoup4  # Add any other dependencies your script needs

        - name: run json py file
          run : |
                python json_load.py
      